### ISSUE TITLE
[Enchancement] Use local stylelint install if available

### ISSUE THREAD

**Issue by JonathanWolfe** [shinnn/stylelint-vscode#3] opened 2017-02-02 15:39 UTC
Haven't looked into how to do this with VS Code yet, but it'd be nice if the plugin would check for and use any local stylelint (in project root or `npm install -g`) installs before bringing in the pre-packaged version.

**Comment by shinnn** [comment] 2017-02-10 16:27
Duplicate of https://github.com/shinnn/stylelint-vscode/issues/2.

**Closed by shinnn** 2017-02-10 16:27 UTC
