### ISSUE TITLE
Provide an ability to configure the extension to use `stylelint` package installed in `node_modules` directory

### ISSUE THREAD

**Issue by skhilko** [shinnn/stylelint-vscode#8] opened 2017-08-03 04:19 UTC
We use `stylelint` package as a dev dependency of our project to run the validation as a pre-commit hook. The latest update of `stylelint-vscode` includes a hard dependency on `stylelint` v8 which includes breaking changes in the rules. That makes the editor choke on our config file.

While we could upgrade the project dependency, this is an unwanted change imposed on VS Code users by the extension.

Please provide a configuration option for the plugin to use the binary of `stylelint` installed in the project. I my opinion, that should be the default behavior. Use for the local binary, and if it doesn't exist, use the default brought in by VS Code extension.

**Comment by shinnn** [comment] 2017-08-03 04:21
Duplicate of https://github.com/shinnn/stylelint-vscode/issues/3

**Closed by shinnn** 2017-08-03 04:21 UTC

**Comment by skhilko** [comment] 2017-08-03 04:24
I assume that the answer is no? I can see there are many closed duplicates for the same issue without real resolution.

**Comment by shinnn** [comment] 2017-08-03 04:26
> I can see there are many closed duplicates for the same issue 

Er, so why did you open this and waste my precious lifetime?
